repos:
  - repo: local
    hooks:
      - id: check-no-docstrings
        name: Check for prohibited docstrings
        entry: check-docstrings
        args: [--fix]
        language: system
        types: [python]
        pass_filenames: true

      - id: check-comment-prefix
        name: Check for non-VA comments
        entry: check-comments
        args: [--fix]
        language: system
        types: [python]
        pass_filenames: true

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.2
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
